
sudo: required

language: php

env:
    global:
        - CONTAINER=bfai_socket
        - IMAGE="moriorgames/socket-server"

services:
    - docker

before_install:
    - docker pull $IMAGE
    - docker build -t $IMAGE .
    - docker run -td --name $CONTAINER $IMAGE

script: docker exec -ti $CONTAINER bash -c 'php phars/phpunit.phar --testdox'

after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker tag $IMAGE "${IMAGE}:${TRAVIS_COMMIT}"
    - docker tag $IMAGE "${IMAGE}:latest"
    - docker push "${IMAGE}:latest"
    - docker push "${IMAGE}:${TRAVIS_COMMIT}"
