#!/usr/bin/php
<?php

require __DIR__ . '/vendor/autoload.php';

use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use App\Services\SocketServer;

$port = 5100;

$server = IoServer::factory(
    new HttpServer(
        new WsServer(
            new SocketServer
        )
    ),
    $port
);

$server->run();
